spring.application.name=EventManagment
spring.output.ansi.enabled=ALWAYS
#server.error.include-message=always
springdoc.swagger-ui.url=/openapi.yaml
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.password=root
spring.datasource.username=postgres1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
