spring.application.name=EventManagment
spring.output.ansi.enabled=ALWAYS

springdoc.swagger-ui.url=/openapi.yaml
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.password=root
spring.datasource.username=postgres1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
event.stats.cron=0 * * * * *
jwt.lifetime=86400000
jwt.secret-key=78Wrc/XhQnIPPJgBWYstVpTlO0o83958LK48M1H8YMmLmQSjtYpMONdWBLA=
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.IntegerSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

